[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y --no-install-recommends tesseract-ocr && pip3 install --upgrade pip && pip3 install -r Requirements.txt"

[deploy]
startCommand = "python3 start.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3